const { db } = require("../services/firestore");
const { getAuth } = require("firebase-admin/auth");
const { app } = require("../config/firebase");
const { requireAuth } = require("../middleware/auth");
const { getAccessState } = require("../services/access");
const { analyzeTradingMarket } = require("../services/tradingEngine");
const { fetchTicker } = require("../trading/data/marketData");
const { getLatestScanResults } = require("../scanner/runner");
function json(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":process.env.FRONTEND_URL||"*","Access-Control-Allow-Headers":"Content-Type, Authorization, X-API-Key, X-KitSetups-Device","Access-Control-Allow-Methods":"GET,OPTIONS"});res.end(JSON.stringify(data));}
function symbol(v){return String(v||"BTCUSDT").trim().toUpperCase();}
function normalize(raw,access,degraded=false){const s=raw||{};const q=s.quality||{};const context=s.evidence?.context||s.context||null;const structures=s.evidence?.structures||s.structures||null;const momentum=s.evidence?.momentum||s.momentum||null;const liquidity=s.evidence?.liquidity||s.liquidity||null;const entry=s.evidence?.entry||s.entry||null;const stop=s.evidence?.stop||s.stop||null;const targets=s.evidence?.targets||s.targets||null;const price=Number(s.price);return {symbol:symbol(s.symbol),timeframe:s.timeframe||"multi-timeframe",timestamp:s.generatedAt||s.updatedAt||new Date().toISOString(),market:{price:Number.isFinite(price)?price:null,trend:context?.bias||s.trend||null,regime:s.regime||s.market?.regime||null,volatility:s.market?.volatility||null,change24hPercent:Number(s.ticker?.change24hPercent),volume24h:Number(s.ticker?.volume24h)},technical:{context,structure:structures,momentum,liquidity},levels:{support:s.levels?.support||[],resistance:s.levels?.resistance||[],entryZone:s.entryZone||(entry?.price!=null?[entry.price,entry.price]:[]),entry:entry?.price??s.entry??null,invalidation:stop?.stop??s.stop??s.invalidation??null,stop:stop?.stop??s.stop??null,targets:targets?.targets||s.targets||[]},setup:{direction:String(s.direction||s.bias||s.setup?.direction||"").toUpperCase()||null,confidence:Number(q.score??s.confidence??0),score:Number(q.score??s.score??0),grade:q.grade||null,detection:s.setup||null},confluence:Array.isArray(q.components)?q.components:Object.entries(q.components||{}).map(([factor,weight])=>({factor,signal:null,weight})),risk:{riskLevel:s.risk?.riskLevel||null,invalidation:stop?.stop??s.stop??s.invalidation??null,warnings:s.risk?.warnings||[]},decision:{status:String(s.status||s.signalState||s.lifecycle?.status||"WAIT").toUpperCase(),valid:s.valid===true,score:Number(q.score??s.score??0),reason:s.reason||s.reasons?.[0]||null},evidence:{context,structures,liquidity,momentum,setup:s.setup||null,entry,stop,targets},lifecycle:s.lifecycle||null,reasons:Array.isArray(s.reasons)?s.reasons:[],generatedAt:s.generatedAt||null,source:degraded?"live-trading-engine-degraded":"live-trading-engine",access,subscribeRequired:!access.hasAccess,degraded};}
function protectSetup(setup){const safe=JSON.parse(JSON.stringify(setup||{}));delete safe.entry;delete safe.stop;delete safe.target;delete safe.entryZone;delete safe.riskReward;if(Array.isArray(safe.targets))safe.targets=safe.targets.map(t=>{const x={...t};delete x.price;delete x.riskReward;return x;});if(safe.lifecycle?.targets)safe.lifecycle.targets=safe.lifecycle.targets.map(t=>{const x={...t};delete x.price;return x;});return safe;}
async function accessFor(req){try{const snap=await db.collection("users").doc(req.user.uid).get();if(snap.exists)return getAccessState(snap.data());}catch(error){console.warn("⚠️ Safe analysis account read unavailable:",error.message||error);}try{const u=await getAuth(app).getUser(req.user.uid);const created=u?.metadata?.creationTime;if(created)return getAccessState({id:req.user.uid,email:u.email||"",displayName:u.displayName||"",plan:"free",trialStartedAt:created,createdAt:created,trialEndsAt:new Date(new Date(created).getTime()+3*86400000).toISOString()});}catch(error){console.warn("⚠️ Safe analysis auth fallback unavailable:",error.message||error);}return getAccessState(null);}
async function livePrice(sym){try{const t=await fetchTicker(sym);return Number.isFinite(Number(t?.lastPrice))?Number(t.lastPrice):null;}catch(error){return null;}}
async function setupById(id){const memory=getLatestScanResults();if(Array.isArray(memory)){const hit=memory.find(s=>String(s?.signalId||s?.id||s?.symbol||"")===String(id)||String(s?.symbol||"")===String(id).toUpperCase());if(hit)return hit;}try{const latest=await db.collection("signals").doc("latest").get();if(latest.exists){const data=latest.data()||{};const list=Array.isArray(data.signals)?data.signals:Array.isArray(data.scanResults)?data.scanResults:[];const hit=list.find(s=>String(s?.signalId||s?.id||s?.symbol||"")===String(id)||String(s?.symbol||"")===String(id).toUpperCase());if(hit)return hit;}}catch(error){console.warn("⚠️ Safe setup lookup unavailable:",error.message||error);}return null;}
async function safeRoutes(req,res){if(req.method!=="GET"||!req.url.startsWith("/api/analysis"))return false;const url=new URL(req.url,"http://localhost");const path=url.pathname;const setupMatch=path.match(/^\/api\/analysis\/setups\/([^/]+)$/);const marketPath=path==="/api/analysis/market"||path==="/api/analysis";if(!setupMatch&&!marketPath)return false;return requireAuth(req,res,async()=>{const access=await accessFor(req);try{if(setupMatch){const id=decodeURIComponent(setupMatch[1]);const setup=await setupById(id);if(!setup)return json(res,404,{ok:false,error:"Setup analysis not found",code:"ANALYSIS_SETUP_NOT_FOUND"});const analysis=normalize(setup,access,!access.hasAccess);const safeSetup=access.hasAccess?setup:protectSetup(setup);if(!access.hasAccess){delete analysis.levels.entry;delete analysis.levels.entryZone;delete analysis.levels.stop;delete analysis.levels.invalidation;delete analysis.levels.targets;delete analysis.setup.riskReward;delete analysis.risk.invalidation;}return json(res,200,{ok:true,data:{analysis,setup:safeSetup,access,subscribeRequired:!access.hasAccess}});}const sym=symbol(url.searchParams.get("symbol"));if(!access.hasAccess){const p=await livePrice(sym);const analysis={...normalize({symbol:sym,price:p,generatedAt:new Date().toISOString(),status:"WAIT",valid:false,reasons:["Live market price is available. Full trade levels require active access."]},access,true),decision:{status:"WAIT",valid:false,score:0,reason:"Live market price is available. Full trade levels require active access."},degraded:true};return json(res,200,{ok:true,data:{analysis,access,subscribeRequired:true,degraded:true}});}const raw=await analyzeTradingMarket(sym);return json(res,200,{ok:true,data:{analysis:normalize(raw,access,false),access,subscribeRequired:false,degraded:false}});}catch(error){console.error("⚠️ Safe analysis fallback:",error.stack||error.message||error);const sym=symbol(url.searchParams.get("symbol"));const p=await livePrice(sym);const analysis=normalize({symbol:sym,price:p,generatedAt:new Date().toISOString(),status:"WAIT",valid:false,reasons:["Live market data is available, but the technical engine is temporarily unavailable."]},access,true);return json(res,200,{ok:true,data:{analysis,access,subscribeRequired:!access.hasAccess,degraded:true}});}});}
module.exports={safeRoutes};
