'use strict';

const TIMEFRAMES = Object.freeze(['1w','1d','4h','1h','30m']);
const HIERARCHY = Object.freeze({macro:'1w',primary:'1d',intermediate:'4h',trade:'1h',execution:'30m'});
const DIRECTIONS = Object.freeze(['LONG','SHORT']);
const SETUP_STATES = Object.freeze(['WAIT','READY']);
const LIFECYCLE_STATES = Object.freeze(['READY','ENTRY_HIT','ACTIVE','TP1_HIT','TP2_HIT','TP3_HIT','STOP_LOSS','MISSED','CLOSED']);
const MINIMUM_RISK_REWARD = 2;
const isDirection=v=>DIRECTIONS.includes(v);
const isTimeframe=v=>TIMEFRAMES.includes(v);
const isFiniteNumber=v=>Number.isFinite(Number(v));
function calculateRiskReward({entry,stop,target}){const e=Number(entry),s=Number(stop),t=Number(target),risk=Math.abs(e-s),reward=Math.abs(t-e);return isFiniteNumber(risk)&&isFiniteNumber(reward)&&risk>0?Number((reward/risk).toFixed(4)):null;}
function validatePriceLevels({direction,entry,stop,targets}){if(!isDirection(direction))return{valid:false,reason:'Invalid direction'};if(!isFiniteNumber(entry)||!isFiniteNumber(stop))return{valid:false,reason:'Entry and stop must be finite numbers'};if(!Array.isArray(targets)||!targets.length)return{valid:false,reason:'At least one target is required'};const e=Number(entry),s=Number(stop);if((direction==='LONG'&&s>=e)||(direction==='SHORT'&&s<=e))return{valid:false,reason:'Stop is on the wrong side of entry'};for(const target of targets){const p=Number(target?.price);if(!isFiniteNumber(p))return{valid:false,reason:'Invalid target price'};if(direction==='LONG'&&p<=e)return{valid:false,reason:'LONG target must be above entry'};if(direction==='SHORT'&&p>=e)return{valid:false,reason:'SHORT target must be below entry'};}return{valid:true,reason:null};}
function createWaitResult({symbol,price,reasons=[],analysis=null,stage=null}){return{symbol,price,status:'WAIT',valid:false,direction:null,entry:null,stop:null,targets:[],riskReward:null,quality:null,reasons:Array.isArray(reasons)?reasons:[],stage,analysis,lifecycle:null,generatedAt:new Date().toISOString()};}
function createSetupResult({symbol,price,direction,entry,stop,targets,quality,reasons=[]}){const validation=validatePriceLevels({direction,entry,stop,targets});if(!validation.valid)throw new Error(`Invalid setup contract: ${validation.reason}`);const normalizedTargets=targets.map((target,index)=>({...target,index:index+1,price:Number(target.price),riskReward:isFiniteNumber(target.riskReward)?Number(target.riskReward):calculateRiskReward({entry,stop,target:target.price})}));return{symbol,price,status:'READY',valid:true,direction,entry:Number(entry),stop:Number(stop),targets:normalizedTargets,riskReward:normalizedTargets[0]?.riskReward??null,quality:quality||null,reasons:Array.isArray(reasons)?reasons:[],lifecycle:{status:'READY',entryHit:false,entryHitAt:null,targets:normalizedTargets.map(t=>({index:t.index,price:t.price,hit:false,hitAt:null})),stopLossHit:false,stopLossHitAt:null,outcome:null,closedAt:null,lastPrice:Number(price),lastCheckedAt:new Date().toISOString()},generatedAt:new Date().toISOString()};}
module.exports={TIMEFRAMES,HIERARCHY,DIRECTIONS,SETUP_STATES,LIFECYCLE_STATES,MINIMUM_RISK_REWARD,isDirection,isTimeframe,isFiniteNumber,validatePriceLevels,calculateRiskReward,createWaitResult,createSetupResult};
