'use strict';
const TIMEFRAMES=Object.freeze(['1w','1d','4h','1h','30m']);
const HIERARCHY=Object.freeze({macro:'1w',primary:'1d',intermediate:'4h',trade:'1h',execution:'30m'});
const DIRECTIONS=Object.freeze(['LONG','SHORT']);
const SETUP_STATES=Object.freeze(['WAIT','READY']);
const LIFECYCLE_STATES=Object.freeze(['READY','ENTRY_HIT','ACTIVE','TP1_HIT','TP2_HIT','TP3_HIT','STOP_LOSS','MISSED','EXPIRED','CLOSED']);
const MINIMUM_RISK_REWARD=1.5;
const isDirection=v=>DIRECTIONS.includes(v); const isTimeframe=v=>TIMEFRAMES.includes(v); const isFiniteNumber=v=>Number.isFinite(Number(v));
function calculateRiskReward({entry,stop,target}){const e=Number(entry),s=Number(stop),t=Number(target),risk=Math.abs(e-s),reward=Math.abs(t-e);return risk>0&&Number.isFinite(reward)?Number((reward/risk).toFixed(4)):null;}
function validatePriceLevels({direction,entry,stop,targets}){if(!isDirection(direction))return{valid:false,reason:'Invalid direction'};if(!isFiniteNumber(entry)||!isFiniteNumber(stop))return{valid:false,reason:'Entry and stop must be finite numbers'};const e=Number(entry),s=Number(stop);if((direction==='LONG'&&s>=e)||(direction==='SHORT'&&s<=e))return{valid:false,reason:'Stop is on the wrong side of entry'};if(!Array.isArray(targets)||!targets.length)return{valid:false,reason:'At least one target is required'};for(const t of targets){const p=Number(t?.price);if(!Number.isFinite(p))return{valid:false,reason:'Invalid target price'};if(direction==='LONG'&&p<=e)return{valid:false,reason:'LONG target must be above entry'};if(direction==='SHORT'&&p>=e)return{valid:false,reason:'SHORT target must be below entry'}}return{valid:true,reason:null};}
function createWaitResult({symbol,price,reasons=[],analysis=null,stage='decision',context=null,structures=null,liquidity=null,momentum=null}){const primary=Array.isArray(reasons)&&reasons.length?reasons[0]:'No sufficiently coherent opportunity';return{symbol,price:Number.isFinite(Number(price))?Number(price):null,status:'WAIT',valid:false,direction:null,setupType:null,marketRegime:context?.regime||null,timeframe:null,entry:null,stop:null,risk:null,targets:[],riskReward:null,quality:{score:0,grade:'D',confidence:'Low',components:{}},thesis:{structural:'',liquidity:'',entry:'',invalidation:''},reasons:[primary,...reasons.slice(1,4)],stage,analysis:{context,structures,liquidity,momentum},lifecycle:null,generatedAt:new Date().toISOString()};}
function createSetupResult({symbol,price,direction,setupType,timeframe,marketRegime,entry,stop,targets,quality,thesis,reasons,context,structures,liquidity,momentum}){const v=validatePriceLevels({direction,entry,stop,targets});if(!v.valid)throw new Error(`Invalid setup contract: ${v.reason}`);const normalized=targets.map((t,i)=>({...t,index:i+1,price:Number(t.price),riskReward:calculateRiskReward({entry,stop,target:t.price})}));return{symbol,price:Number(price),status:'READY',valid:true,direction,setupType,marketRegime,timeframe,entry:Number(entry),stop:Number(stop),risk:Number(Math.abs(Number(entry)-Number(stop))),targets:normalized,riskReward:normalized[0]?.riskReward??null,quality,thesis,reasons:[...new Set((reasons||[]).filter(Boolean))],analysis:{context,structures,liquidity,momentum},lifecycle:{status:'READY',entryHit:false,entryHitAt:null,targets:normalized.map(t=>({index:t.index,price:t.price,hit:false,hitAt:null})),stopLossHit:false,stopLossHitAt:null,outcome:null,closedAt:null,lastPrice:Number(price),lastCheckedAt:new Date().toISOString()},generatedAt:new Date().toISOString()};}
module.exports={TIMEFRAMES,HIERARCHY,DIRECTIONS,SETUP_STATES,LIFECYCLE_STATES,MINIMUM_RISK_REWARD,isDirection,isTimeframe,isFiniteNumber,validatePriceLevels,calculateRiskReward,createWaitResult,createSetupResult};
