'use strict';
const {getMarketData}=require('./data/marketData');
const {analyzeContext}=require('./analysis/context');
const {analyzeAllStructures}=require('./analysis/structure');
const {analyzeAllLiquidity}=require('./analysis/liquidity');
const {analyzeMomentum}=require('./analysis/momentum');
const {detectSetup}=require('./setup/detector');
const {calculateEntry}=require('./setup/entry');
const {calculateStop}=require('./setup/stop');
const {buildTargets}=require('./setup/targets');
const {scoreSetup}=require('./quality/scorer');
const {validatePriceLevels,MINIMUM_RISK_REWARD,createWaitResult}=require('./contract');
function reject(symbol,price,stage,reason,analysis={}){return createWaitResult({symbol,price,reasons:[reason],analysis,stage});}
function buildFinalSetup({marketData,context,structures,liquidity,momentum,setup,entry,stop,targets,quality}){const validation=validatePriceLevels({direction:setup.direction,entry:entry.price,stop:stop.stop,targets:targets.targets});if(!validation.valid)return reject(marketData.symbol,Number(marketData.ticker.lastPrice),'finalValidation',validation.reason,{context,structures,liquidity,momentum,setup,entry,stop,targets,quality});if(Number(targets.targets[0]?.riskReward)<MINIMUM_RISK_REWARD)return reject(marketData.symbol,Number(marketData.ticker.lastPrice),'finalValidation','TP1 does not satisfy minimum 2R',{context,structures,liquidity,momentum,setup,entry,stop,targets,quality});return{symbol:marketData.symbol,price:Number(marketData.ticker.lastPrice),status:'READY',valid:true,direction:setup.direction,entry:entry.price,stop:stop.stop,targets:targets.targets,riskReward:targets.riskReward,quality:{score:quality.score,grade:quality.grade,components:quality.components},reasons:[...setup.reasons,entry.reason,stop.reason,targets.reason,...quality.reasons],evidence:{context,structures,liquidity,momentum,setup,entry,stop,targets},lifecycle:{status:'READY',entryHit:false,entryHitAt:null,targets:targets.targets.map(t=>({index:t.index,price:t.price,hit:false,hitAt:null})),stopLossHit:false,stopLossHitAt:null,outcome:null,closedAt:null,lastPrice:Number(marketData.ticker.lastPrice),lastCheckedAt:new Date().toISOString()},generatedAt:new Date().toISOString()};}
async function analyzeSymbol(symbol){if(!symbol)throw new Error('symbol is required');const marketData=await getMarketData(symbol);const price=Number(marketData?.ticker?.lastPrice);if(!Number.isFinite(price))return reject(symbol,null,'marketData','Invalid market price');const context=analyzeContext(marketData);const structures=analyzeAllStructures(marketData);if(!['1w','1d','4h','1h','30m'].every(tf=>context.timeframes?.[tf]?.valid&&structures?.[tf]?.valid))return reject(symbol,price,'structure','Insufficient closed-candle data for the full timeframe hierarchy',{context,structures});const liquidity=analyzeAllLiquidity(marketData,structures);const momentum=analyzeMomentum(marketData.timeframes);const setup=detectSetup({symbol,price,context,structures,liquidity,momentum});if(!setup?.detected)return reject(symbol,price,'detector',setup?.reasons?.[0]||'No valid setup detected',{context,structures,liquidity,momentum,setup});setup.executionCandle=marketData.timeframes['30m']?.candles?.at(-1)||null;const entry=calculateEntry({direction:setup.direction,price,structures,setup});if(!entry.valid)return reject(symbol,price,'entry',entry.reason,{context,structures,liquidity,momentum,setup,entry});const stop=calculateStop({direction:setup.direction,entry:entry.price,structures});if(!stop.valid)return reject(symbol,price,'stop',stop.reason,{context,structures,liquidity,momentum,setup,entry,stop});const targets=buildTargets({entry:entry.price,stop:stop.stop,direction:setup.direction,liquidity});if(!targets.valid)return reject(symbol,price,'targets',targets.reason,{context,structures,liquidity,momentum,setup,entry,stop,targets});const quality=scoreSetup({direction:setup.direction,context,structures,liquidity,momentum,setup,riskReward:targets.riskReward,entry:entry.price});if(!quality.valid)return reject(symbol,price,'quality','Setup quality below publication threshold',{context,structures,liquidity,momentum,setup,entry,stop,targets,quality});return buildFinalSetup({marketData,context,structures,liquidity,momentum,setup,entry,stop,targets,quality});}
module.exports={analyzeSymbol,buildFinalSetup,reject};
