'use strict';
const {getMarketData}=require('./data/marketData');
const {analyzeContext}=require('./analysis/context');
const {analyzeAllStructures}=require('./analysis/structure');
const {analyzeAllLiquidity}=require('./analysis/liquidity');
const {analyzeMomentum}=require('./analysis/momentum');
const {createWaitResult,createSetupResult,validatePriceLevels,calculateRiskReward}=require('./contract');
const n=v=>Number(v), finite=v=>Number.isFinite(n(v));
function wait(symbol,price,stage,reason,p){return createWaitResult({symbol,price,stage,reasons:[reason],context:p?.context,structures:p?.structures,liquidity:p?.liquidity,momentum:p?.momentum})}
function directional(x,d){return x?.direction===(d==='LONG'?'bullish':'bearish')}
function latestBreak(s,d){return ['30m','1h','4h','1d'].map(tf=>({tf,b:s?.[tf]?.breaks?.latest})).filter(x=>x.b&&x.b.direction===(d==='LONG'?'bullish':'bearish')).sort((a,b)=>n(b.b.index)-n(a.b.index))[0]||null}
function latestSweep(l,d){const side=d==='LONG'?'sell_side':'buy_side';return ['30m','1h','4h','1d'].flatMap(tf=>(l?.[tf]?.sweeps||[]).map(x=>({...x,timeframe:tf}))).filter(x=>x.side===side).sort((a,b)=>n(b.candleIndex)-n(a.candleIndex))[0]||null}
function chooseSetup({context,structures,liquidity,momentum}){const bias=context.bias==='bullish'?'LONG':context.bias==='bearish'?'SHORT':null,c=[];for(const d of ['LONG','SHORT']){const macro=['1w','1d','4h'].filter(tf=>directional(structures[tf],d)).length,exec=['1h','30m'].filter(tf=>directional(structures[tf],d)).length,mom=['1h','30m'].filter(tf=>momentum?.timeframes?.[tf]?.direction===(d==='LONG'?'bullish':'bearish')).length,br=latestBreak(structures,d),sw=latestSweep(liquidity,d),range=['ranging','consolidating'].includes(context.regime);let type=null,base=0,reasons=[];if(sw&&br&&n(br.b.index)>=n(sw.candleIndex)){type='REVERSAL';base=34;reasons.push(`${sw.timeframe} liquidity sweep followed by ${br.b.kind}`)}else if(br){type='CONTINUATION';base=28;reasons.push(`${br.tf} ${br.b.kind} confirms directional structure`)}else if(range&&sw){type='RANGE_REVERSAL';base=28;reasons.push('Range liquidity sweep offers a reversal location')}else if(macro>=2&&exec>=1){type='PULLBACK';base=24;reasons.push('Directional structure supports a pullback opportunity')}if(!type)continue;let score=base+macro*7+exec*6+mom*5+(bias===d?12:0)+(sw?8:0);if(context.regime==='trending'&&type==='CONTINUATION')score+=7;if(context.regime==='transitioning'&&type==='REVERSAL')score+=8;if(context.regime==='expanding')score+=3;if(macro===0)score-=10;if(exec===0)score-=5;c.push({direction:d,type,score:Math.min(100,score),break:br,sweep:sw,macro,exec,mom,reasons})}c.sort((a,b)=>b.score-a.score);return c[0]||null}
function chooseEntry({price,setup,structures}){const d=setup.direction,br=setup.break?.b;if(setup.sweep&&br){const level=n(br.level);if(Math.abs(price-level)/(Math.abs(price)||1)<.012)return{price,mode:'retest',reference:{timeframe:setup.break.tf,level,type:br.kind},reason:'Price is interacting with the confirmed structural level after the liquidity event'};}if(br){const level=n(br.level);if((d==='LONG'&&price>level)||(d==='SHORT'&&price<level))return{price,mode:'continuation',reference:{timeframe:setup.break.tf,level,type:br.kind},reason:`Price remains beyond the ${br.kind} level`};}const sw=d==='LONG'?structures['30m']?.latest?.low:structures['30m']?.latest?.high;if(sw&&finite(sw.price)&&Math.abs(price-n(sw.price))/(Math.abs(price)||1)<.008)return{price,mode:'pullback',reference:{timeframe:'30m',level:n(sw.price)},reason:'Price is near the latest execution swing'};return null}
function chooseStop({entry,setup,structures}){const d=setup.direction,keys=d==='LONG'?['30m','1h','4h'].map(tf=>({tf,p:structures[tf]?.protectedLow?.price})):['30m','1h','4h'].map(tf=>({tf,p:structures[tf]?.protectedHigh?.price}));const c=keys.filter(x=>finite(x.p)&&(d==='LONG'?n(x.p)<entry:n(x.p)>entry));if(!c.length)return null;const x=c[0];return{stop:n(x.p),reference:{timeframe:x.tf,structuralLevel:n(x.p)},reason:d==='LONG'?`Structural invalidation below the ${x.tf} protected low`:`Structural invalidation above the ${x.tf} protected high`}}
function chooseTargets({entry,stop,direction,liquidity}){const d=[];for(const tf of ['30m','1h','4h','1d','1w'])for(const x of (direction==='LONG'?liquidity?.[tf]?.buySide:liquidity?.[tf]?.sellSide)||[]){const p=n(x.price);if(!finite(p)||x.swept===true||(direction==='LONG'?p<=entry:p>=entry))continue;const rr=calculateRiskReward({entry,stop,target:p});if(rr)d.push({...x,price:p,timeframe:tf,riskReward:rr})}return[...new Map(d.map(x=>[`${x.price.toFixed(8)}:${x.side}`,x])).values()].sort((a,b)=>direction==='LONG'?a.price-b.price:b.price-a.price).slice(0,3)}
function score({setup,context,structures,momentum,entry,stop,targets}){const d=setup.direction,exp=d==='LONG'?'bullish':'bearish',macro=['1w','1d','4h'].filter(tf=>directional(structures[tf],d)).length,exec=['1h','30m'].filter(tf=>directional(structures[tf],d)).length,mom=['1h','30m'].filter(tf=>momentum?.timeframes?.[tf]?.direction===exp).length,rr=targets[0]?.riskReward||0,riskPct=Math.abs(entry-stop)/(entry||1),liq=targets.length?Math.min(100,45+targets.filter(t=>t.liquidityClass==='external').length*20):0;const components={higherTimeframe:macro/3*22,executionStructure:exec/2*15,liquidity:liq*.18,entryQuality:setup.score*.15,momentum:mom/2*12,regime:context.regime==='unknown'?4:context.regime==='expanding'?8:12,stopQuality:riskPct<.025?10:riskPct<.05?7:4,targetQuality:targets.length?8:0,rr:rr>=3?10:rr>=2?8:rr>=1.5?5:0,freshness:setup.break||setup.sweep?6:2,structuralClarity:Math.round((structures['30m']?.clarity||0)*.05)};let total=Math.round(Object.values(components).reduce((a,b)=>a+b,0));const bias=context.bias==='bullish'?'LONG':context.bias==='bearish'?'SHORT':null;if(bias&&bias!==d)total=Math.max(0,total-6);return{score:Math.min(100,total),grade:total>=90?'A+':total>=80?'A':total>=68?'B':total>=56?'C':'D',confidence:total>=80?'High conviction':total>=68?'Strong':total>=56?'Moderate':'Low',components,reasons:[...setup.reasons,macro===3?'Higher-timeframe structure is aligned':`${macro}/3 higher timeframes support the direction`,`${exec}/2 execution timeframes support the direction`,`${mom}/2 execution momentum readings support the direction`,rr?`${rr.toFixed(2)}R to TP1`:'Target quality is limited']}}
function buildFinal({marketData,context,structures,liquidity,momentum,setup,entry,stop,targets,quality}){const v=validatePriceLevels({direction:setup.direction,entry,stop,targets});if(!v.valid)return wait(marketData.symbol,marketData.ticker.lastPrice,'finalValidation',v.reason,{context,structures,liquidity,momentum});const thesis={structural:`${setup.type} built from ${setup.reasons[0]||'current structure'}.`,liquidity:setup.sweep?'Recent opposing liquidity was swept before the structural response.':targets[0]?'Unswept directional liquidity provides the objective.':'Liquidity is present but limited.',entry:`Entry is derived from the ${setup.type.toLowerCase()} model and current chart price.`,invalidation:`Setup invalidates at ${stop}.`};return createSetupResult({symbol:marketData.symbol,price:marketData.ticker.lastPrice,direction:setup.direction,setupType:setup.type,timeframe:setup.break?.tf||'30m',marketRegime:context.regime,entry,stop,targets,quality,thesis,reasons:quality.reasons,context,structures,liquidity,momentum})}
async function analyzeSymbol(symbol){if(!symbol)throw new Error('symbol is required');const md=await getMarketData(symbol),price=n(md?.ticker?.lastPrice);if(!finite(price))return wait(symbol,null,'marketData','Invalid market price');const context=analyzeContext(md),structures=analyzeAllStructures(md),liquidity=analyzeAllLiquidity(md,structures),momentum=analyzeMomentum(md.timeframes);const missing=['1w','1d','4h','1h','30m'].filter(tf=>!structures[tf]?.valid);if(missing.length>2)return wait(symbol,price,'data',`Insufficient closed-candle data on ${missing.join(', ')}`,{context,structures,liquidity,momentum});const setup=chooseSetup({context,structures,liquidity,momentum});if(!setup)return wait(symbol,price,'decision','No sufficiently coherent opportunity across structure, liquidity, momentum and context',{context,structures,liquidity,momentum});const entry=chooseEntry({price,setup,structures});if(!entry)return wait(symbol,price,'entry',`The ${setup.type.toLowerCase()} thesis is present, but price has not reached a chart-derived entry location`,{context,structures,liquidity,momentum});const stop=chooseStop({entry:entry.price,setup,structures});if(!stop)return wait(symbol,price,'invalidation','No logical structural invalidation level is available on the correct side of entry',{context,structures,liquidity,momentum});const targets=chooseTargets({entry:entry.price,stop:stop.stop,direction:setup.direction,liquidity});if(!targets.length)return wait(symbol,price,'targets','No meaningful unswept directional liquidity remains for a target',{context,structures,liquidity,momentum});const quality=score({setup,context,structures,momentum,entry:entry.price,stop:stop.stop,targets});if(quality.score<56)return wait(symbol,price,'quality','The trade thesis is coherent but its combined evidence is not strong enough to publish',{context,structures,liquidity,momentum});return buildFinal({marketData:md,context,structures,liquidity,momentum,setup,entry:entry.price,stop:stop.stop,targets,quality})}
function buildFinalSetup(args){return buildFinal(args)}
module.exports={analyzeSymbol,buildFinalSetup,reject:wait,LIVE_STATUSES:['READY','ENTRY_HIT','ACTIVE','TP1_HIT','TP2_HIT','TP3_HIT']};
