'use strict';
const {getMarketData}=require('./data/marketData');
const {analyzeContext}=require('./analysis/context');
const {analyzeAllStructures}=require('./analysis/structure');
const {analyzeAllLiquidity}=require('./analysis/liquidity');
const {analyzeMomentum}=require('./analysis/momentum');
const {createWaitResult,createSetupResult,validatePriceLevels,calculateRiskReward}=require('./contract');
const TFS=['1w','1d','4h','1h','30m'];
const LIVE=['READY','ENTRY_HIT','ACTIVE','TP1_HIT','TP2_HIT','TP3_HIT'];
const n=v=>Number(v), finite=v=>Number.isFinite(n(v));
function wait(symbol,price,stage,reason,parts){return createWaitResult({symbol,price,stage,reasons:[reason],context:parts?.context,structures:parts?.structures,liquidity:parts?.liquidity,momentum:parts?.momentum})}
function directional(x,d){return x?.direction===(d==='LONG'?'bullish':'bearish')}
function latestBreak(structures,d){return ['30m','1h','4h','1d'].map(tf=>({tf,b:structures?.[tf]?.breaks?.latest})).filter(x=>x.b&&x.b.direction===(d==='LONG'?'bullish':'bearish')).sort((a,b)=>n(b.b.index)-n(a.b.index))[0]||null}
function latestSweep(liquidity,d){const side=d==='LONG'?'sell_side':'buy_side';return ['30m','1h','4h','1d'].flatMap(tf=>(liquidity?.[tf]?.sweeps||[]).map(s=>({...s,timeframe:tf}))).filter(s=>s.side===side).sort((a,b)=>n(b.candleIndex)-n(a.candleIndex))[0]||null}
function chooseSetup({price,context,structures,liquidity,momentum}){
 const bias=context.bias==='bullish'?'LONG':context.bias==='bearish'?'SHORT':null;
 const dirs=['LONG','SHORT']; const candidates=[];
 for(const d of dirs){const exp=d==='LONG'?'bullish':'bearish', opposite=d==='LONG'?'bearish':'bullish';const macro=['1w','1d','4h'].filter(tf=>directional(structures[tf],d)).length;const exec=['1h','30m'].filter(tf=>directional(structures[tf],d)).length;const mom=['1h','30m'].filter(tf=>momentum?.timeframes?.[tf]?.direction===exp).length;const br=latestBreak(structures,d),sw=latestSweep(liquidity,d);const opposingSweep=!!sw;const range=context.regime==='ranging'||context.regime==='consolidating';
   let type=null,score=0,reasons=[];
   if(sw && br && n(br.b.index)>=n(sw.candleIndex)){type='REVERSAL';score+=34;reasons.push(`${sw.timeframe} liquidity sweep followed by ${br.b.kind}`)}
   else if(br){type='CONTINUATION';score+=28;reasons.push(`${br.tf} ${br.b.kind} confirms directional structure`)}
   else if(range && sw){type='RANGE_REVERSAL';score+=28;reasons.push('Range liquidity sweep offers a reversal location')}
   else if(macro>=2 && exec>=1){type='PULLBACK';score+=24;reasons.push('Directional structure supports a pullback opportunity')}
   if(!type)continue;
   score+=macro*7+exec*6+mom*5+(bias===d?12:0)+(opposingSweep?8:0);
   if(context.regime==='trending'&&type==='CONTINUATION')score+=7;if(context.regime==='transitioning'&&type==='REVERSAL')score+=8;if(context.regime==='expanding')score+=3;
   if(macro===0)score-=10;if(exec===0)score-=5;
   candidates.push({direction:d,type,score:Math.min(100,score),break:br,sweep:sw,macro,exec,mom,reasons});
 }
 candidates.sort((a,b)=>b.score-a.score);const best=candidates[0];if(!best||best.score<34)return null;return best;
}
function chooseEntry({price,setup,structures}){const d=setup.direction,br=setup.break?.b;if(setup.sweep&&br){const level=n(br.level);const near=Math.abs(price-level)/(Math.abs(price)||1);if(near<.012)return{price,mode:'retest',reference:{timeframe:setup.break.tf,level,type:br.kind},reason:'Price is interacting with the confirmed structural level after the liquidity event'} }
 if(br){const level=n(br.level);if((d==='LONG'&&price>level)||(d==='SHORT'&&price<level))return{price,mode:'continuation',reference:{timeframe:setup.break.tf,level,type:br.kind},reason:`Price remains beyond the ${br.kind} level`};}
 const exec=structures['30m'];const sw=d==='LONG'?exec?.latest?.low:exec?.latest?.high;if(sw&&finite(sw.price)){const level=n(sw.price);const near=Math.abs(price-level)/(Math.abs(price)||1);if(near<.008)return{price,mode:'pullback',reference:{timeframe:'30m',level},reason:'Price is near the latest execution swing'} }
 return null;
}
function chooseStop({entry,setup,structures}){const d=setup.direction;const points=d==='LONG'?['30m','1h','4h'].map(tf=>({tf,p:structures[tf]?.protectedLow?.price})):['30m','1h','4h'].map(tf=>({tf,p:structures[tf]?.protectedHigh?.price}));const candidates=points.filter(x=>finite(x.p)&&((d==='LONG'&&n(x.p)<entry)||(d==='SHORT'&&n(x.p)>entry)));if(!candidates.length)return null;const best=candidates[0];return{stop:n(best.p),reference:{timeframe:best.tf,structuralLevel:n(best.p)},reason:`Structural invalidation below the ${best.tf} protected low` .replace('below the','below the').replace('protected low',d==='LONG'?'protected low':'protected high')};}
function chooseTargets({entry,stop,direction,liquidity}){const data=[];for(const tf of ['30m','1h','4h','1d','1w'])for(const x of (direction==='LONG'?liquidity?.[tf]?.buySide:liquidity?.[tf]?.sellSide)||[]){const p=n(x.price);if(!finite(p)||x.swept===true)continue;if(direction==='LONG'&&p<=entry||direction==='SHORT'&&p>=entry)continue;const rr=calculateRiskReward({entry,stop,target:p});if(rr)data.push({...x,price:p,timeframe:tf,riskReward:rr})}const uniq=[...new Map(data.map(x=>[`${x.price.toFixed(8)}:${x.side}`,x])).values()].sort((a,b)=>direction==='LONG'?a.price-b.price:b.price-a.price);return uniq.slice(0,3);}
function score({setup,context,structures,liquidity,momentum,entry,stop,targets}){const d=setup.direction,exp=d==='LONG'?'bullish':'bearish';const macro=['1w','1d','4h'].filter(tf=>directional(structures[tf],d)).length,exec=['1h','30m'].filter(tf=>directional(structures[tf],d)).length,mom=['1h','30m'].filter(tf=>momentum?.timeframes?.[tf]?.direction===exp).length;const nearest=targets[0]?.riskReward||0,stopRisk=Math.abs(entry-stop)/(entry||1);const liq=targets.length?Math.min(100,45+targets.filter(t=>t.liquidityClass==='external').length*20):0;const components={higherTimeframe:macro/3*22,executionStructure:exec/2*15,liquidity:liq*.18,entryQuality:setup.score*.15,momentum:mom/2*12,regime:context.regime==='unknown'?4:context.regime==='expanding'?8:12,stopQuality:stopRisk<.025?10:stopRisk<.05?7:4,targetQuality:targets.length?8:0,rr:nearest>=3?10:nearest>=2?8:nearest>=1.5?5:0,freshness:setup.break||setup.sweep?6:2,structuralClarity:Math.round((structures['30m']?.clarity||0)*.05)};let total=Math.round(Object.values(components).reduce((a,b)=>a+b,0));if(setup.direction!==(context.bias==='bullish'?'LONG':context.bias==='bearish'?'SHORT':setup.direction))total=Math.max(0,total-6);const grade=total>=90?'A+':total>=80?'A':total>=68?'B':total>=56?'C':'D';return{score:Math.min(100,total),grade,confidence:total>=80?'High conviction':total>=68?'Strong':total>=56?'Moderate':'Low',components,reasons:[...setup.reasons,macro===3?'Higher-timeframe structure is aligned':`${macro}/3 higher timeframes support the direction`,`${exec}/2 execution timeframes support the direction`,`${mom}/2 execution momentum readings support the direction`,nearest?`${nearest.toFixed(2)}R to TP1`:'Target quality is limited']};}
function buildFinal({marketData,context,structures,liquidity,momentum,setup,entry,stop,targets,quality}){const v=validatePriceLevels({direction:setup.direction,entry,stop,targets});if(!v.valid)return wait(marketData.symbol,marketData.ticker.lastPrice,'finalValidation',v.reason,{context,structures,liquidity,momentum});const now=new Date().toISOString();const thesis={structural:`${setup.type} built from ${setup.reasons[0]||'current structure'}.`,liquidity:setup.sweep?'Recent opposing liquidity was swept before the structural response.':targets[0]?'Price has a genuine directional liquidity objective above/below entry.':'Liquidity is present but limited.',entry:entry===marketData.ticker.lastPrice?`Entry uses the current chart price via a ${setup.type.toLowerCase()} model.`:'Entry is derived from the execution structure.',invalidation:`Setup invalidates at ${stop}.`};return createSetupResult({symbol:marketData.symbol,price:marketData.ticker.lastPrice,direction:setup.direction,setupType:setup.type,timeframe:setup.break?.tf||'30m',marketRegime:context.regime,entry,stop,targets,quality,thesis,reasons:quality.reasons,context,structures,liquidity,momentum});}
async function analyzeSymbol(symbol){if(!symbol)throw new Error('symbol is required');const md=await getMarketData(symbol),price=n(md?.ticker?.lastPrice);if(!finite(price))return wait(symbol,null,'marketData','Invalid market price');const context=analyzeContext(md),structures=analyzeAllStructures(md),liquidity=analyzeAllLiquidity(md,structures),momentum=analyzeMomentum(md.timeframes);const missing=TFS.filter(tf=>!structures[tf]?.valid);if(missing.length>2)return wait(symbol,price,'data',`Insufficient closed-candle data on ${missing.join(', ')}`,{context,structures,liquidity,momentum});const setup=chooseSetup({price,context,structures,liquidity,momentum});if(!setup)return wait(symbol,price,'decision','No sufficiently coherent opportunity across structure, liquidity, momentum and context',{context,structures,liquidity,momentum});const entry=chooseEntry({price,setup,structures});if(!entry)return wait(symbol,price,'entry',`The ${setup.type.toLowerCase()} thesis is present, but price has not reached a chart-derived entry location`,{context,structures,liquidity,momentum});const stopData=chooseStop({entry:entry.price,setup,structures});if(!stopData)return wait(symbol,price,'invalidation','No logical structural invalidation level is available on the correct side of entry',{context,structures,liquidity,momentum});const targets=chooseTargets({entry:entry.price,stop:stopData.stop,direction:setup.direction,liquidity});if(!targets.length)return wait(symbol,price,'targets','No meaningful unswept directional liquidity remains for a target',{context,structures,liquidity,momentum});const quality=score({setup,context,structures,liquidity,momentum,entry:entry.price,stop:stopData.stop,targets});if(quality.score<56)return wait(symbol,price,'quality','The trade thesis is coherent but its combined evidence is not strong enough to publish',{context,structures,liquidity,momentum});return buildFinal({marketData:md,context,structures,liquidity,momentum,setup,entry:entry.price,stop:stopData.stop,targets,quality});}
function buildFinalSetup(args){return buildFinal(args)}
module.exports={analyzeSymbol,buildFinalSetup,reject:wait,LIVE_STATUSES:LIVE};
