'use strict';
const {TIMEFRAMES}=require('../contract');
function valid(c){return c&&Number.isFinite(Number(c.open))&&Number.isFinite(Number(c.high))&&Number.isFinite(Number(c.low))&&Number.isFinite(Number(c.close))&&c.isClosed!==false;}
function closed(cs){return(Array.isArray(cs)?cs:[]).filter(valid).sort((a,b)=>Number(a.openTime)-Number(b.openTime));}
function avgRange(cs){const r=cs.slice(-20).map(c=>Number(c.high)-Number(c.low)).filter(v=>v>0);return r.length?r.reduce((a,b)=>a+b,0)/r.length:null;}
function pressure(cs){const r=cs.slice(-8);let up=0,down=0;for(const c of r){const b=Math.abs(Number(c.close)-Number(c.open));if(c.close>c.open)up+=b;else if(c.close<c.open)down+=b;}const total=up+down;return total?Number(((up-down)/total).toFixed(4)):0;}
function netMove(cs){if(cs.length<12)return 0;const a=Number(cs.at(-11).close),b=Number(cs.at(-1).close),ar=avgRange(cs);return ar?Number(((b-a)/ar).toFixed(4)):0;}
function analyzeTimeframe(timeframe,candles){const cs=closed(candles);if(cs.length<30)return{timeframe,valid:false,lastPrice:null,averageRange:null,pressure:0,netMoveInRanges:0,bias:'neutral'};const p=pressure(cs),m=netMove(cs);return{timeframe,valid:true,lastPrice:Number(cs.at(-1).close),averageRange:avgRange(cs),pressure:p,netMoveInRanges:m,bias:m>0&&p>0?'bullish':m<0&&p<0?'bearish':'neutral'};}
function analyzeContext(marketData){if(!marketData?.timeframes)throw new Error('Market data with timeframes is required');const timeframes={};for(const tf of TIMEFRAMES)timeframes[tf]=analyzeTimeframe(tf,marketData.timeframes[tf]?.candles||[]);let bullish=0,bearish=0;const weights={'1w':4,'1d':4,'4h':3,'1h':2,'30m':1};for(const tf of TIMEFRAMES){const d=timeframes[tf];if(!d.valid)continue;if(d.bias==='bullish')bullish+=weights[tf];if(d.bias==='bearish')bearish+=weights[tf];}const bias=bullish>bearish?'bullish':bearish>bullish?'bearish':'neutral';return{bias,timeframes,hierarchy:{macro:timeframes['1w'],primary:timeframes['1d'],intermediate:timeframes['4h'],trade:timeframes['1h'],execution:timeframes['30m']},aligned:['1w','1d','4h'].every(tf=>timeframes[tf].valid)&&bias!=='neutral',generatedAt:new Date().toISOString()};}
module.exports={REQUIRED_TIMEFRAMES:TIMEFRAMES,analyzeContext};
