'use strict';
const {TIMEFRAMES}=require('../contract');
function n(v){return Number(v)} function valid(c){return c&&c.isClosed!==false&&[c.open,c.high,c.low,c.close].every(v=>Number.isFinite(Number(v)))}
function closed(cs){return(Array.isArray(cs)?cs:[]).filter(valid).sort((a,b)=>Number(a.openTime)-Number(b.openTime))}
function avgRange(cs){const x=cs.slice(-20).map(c=>n(c.high)-n(c.low)).filter(v=>v>0);return x.length?x.reduce((a,b)=>a+b,0)/x.length:0}
function pressure(cs,lookback=10){let u=0,d=0;for(const c of cs.slice(-lookback)){const b=Math.abs(n(c.close)-n(c.open));if(n(c.close)>n(c.open))u+=b;else d+=b}return u+d?((u-d)/(u+d))*100:0}
function trendScore(cs){if(cs.length<30)return{direction:'neutral',strength:0};const recent=cs.slice(-20),old=cs.slice(-40,-20);const r=recent.reduce((a,c)=>a+n(c.close),0)/recent.length,o=old.reduce((a,c)=>a+n(c.close),0)/old.length,ar=avgRange(cs);const delta=ar?(r-o)/ar:0;const p=pressure(cs);const score=Math.min(100,Math.round(Math.abs(delta)*12+Math.abs(p)*.65));return{direction:delta>.35&&p>0?'bullish':delta<-.35&&p<0?'bearish':'neutral',strength:score,delta:Number(delta.toFixed(3)),pressure:Number(p.toFixed(2))}}
function regime(cs){const ar=avgRange(cs),short=avgRange(cs.slice(-5)),base=avgRange(cs.slice(-30));if(!ar||!base)return'unknown';const ratio=short/base;const t=trendScore(cs);if(ratio>=1.35)return'expanding';if(ratio<=.72&&t.direction==='neutral')return'consolidating';if(t.direction==='neutral')return'ranging';if(Math.abs(t.delta||0)<.7)return'transitioning';return'trending'}
function analyzeTimeframe(timeframe,candles){const cs=closed(candles);if(cs.length<30)return{timeframe,valid:false,trend:'neutral',bias:'neutral',strength:0,momentum:0,volatility:'unknown',averageRange:null,keyLevels:{high:null,low:null}};const t=trendScore(cs),ar=avgRange(cs);return{timeframe,valid:true,trend:t.direction,bias:t.direction,strength:t.strength,momentum:t.pressure,volatility:regime(cs),averageRange:Number(ar.toFixed(8)),keyLevels:{high:n(cs.slice(-20).reduce((a,c)=>n(c.high)>n(a.high)?c:a).high),low:n(cs.slice(-20).reduce((a,c)=>n(c.low)<n(a.low)?c:a).low)}}}
function analyzeContext(marketData){if(!marketData?.timeframes)throw new Error('Market data with timeframes is required');const timeframes={};for(const tf of TIMEFRAMES)timeframes[tf]=analyzeTimeframe(tf,marketData.timeframes[tf]?.candles||[]);const w={ '1w':4,'1d':4,'4h':3,'1h':2,'30m':1};let bull=0,bear=0;for(const tf of TIMEFRAMES){if(timeframes[tf].trend==='bullish')bull+=w[tf];if(timeframes[tf].trend==='bearish')bear+=w[tf]}const bias=bull>bear?'bullish':bear>bull?'bearish':'neutral';const regimes=Object.values(timeframes).map(x=>x.volatility);const regimeName=regimes.includes('expanding')?'expanding':regimes.includes('transitioning')?'transitioning':regimes.includes('trending')?'trending':regimes.filter(x=>x!=='unknown').every(x=>x==='consolidating')?'consolidating':'ranging';return{bias,regime:regimeName,timeframes,hierarchy:{macro:timeframes['1w'],primary:timeframes['1d'],intermediate:timeframes['4h'],trade:timeframes['1h'],execution:timeframes['30m']},alignment:{bullish:bull,bearish:bear,score:Math.min(100,Math.round(Math.abs(bull-bear)/14*100))},generatedAt:new Date().toISOString()}}
module.exports={REQUIRED_TIMEFRAMES:TIMEFRAMES,analyzeContext};
