'use strict';
const TIMEFRAMES=Object.freeze(['1w','1d','4h','1h','30m']);
const DEFAULT_SWING_LENGTH=2;
function valid(c){return c&&c.isClosed!==false&&Number.isFinite(Number(c.high))&&Number.isFinite(Number(c.low))&&Number.isFinite(Number(c.close));}
function closed(cs){return(Array.isArray(cs)?cs:[]).filter(valid).sort((a,b)=>Number(a.openTime)-Number(b.openTime));}
function findSwingHighs(cs,strength=2){const d=closed(cs),out=[];for(let i=strength;i<d.length-strength;i++){const h=Number(d[i].high);let ok=true;for(let j=1;j<=strength;j++)if(h<=Number(d[i-j].high)||h<=Number(d[i+j].high)){ok=false;break;}if(ok)out.push({type:'swing_high',price:h,index:i,time:d[i].openTime});}return out;}
function findSwingLows(cs,strength=2){const d=closed(cs),out=[];for(let i=strength;i<d.length-strength;i++){const l=Number(d[i].low);let ok=true;for(let j=1;j<=strength;j++)if(l>=Number(d[i-j].low)||l>=Number(d[i+j].low)){ok=false;break;}if(ok)out.push({type:'swing_low',price:l,index:i,time:d[i].openTime});}return out;}
function classifyHighs(xs){return xs.map((x,i)=>({...x,classification:i===0?'SH':x.price>xs[i-1].price?'HH':x.price<xs[i-1].price?'LH':'EQH',side:'buy_side'}));}
function classifyLows(xs){return xs.map((x,i)=>({...x,classification:i===0?'SL':x.price>xs[i-1].price?'HL':x.price<xs[i-1].price?'LL':'EQL',side:'sell_side'}));}
function determineDirection(highs,lows){const h=highs.slice(-3),l=lows.slice(-3);const bull=h.filter(x=>x.classification==='HH').length+l.filter(x=>x.classification==='HL').length;const bear=h.filter(x=>x.classification==='LH').length+l.filter(x=>x.classification==='LL').length;return bull>=2&&bull>bear?'bullish':bear>=2&&bear>bull?'bearish':'range';}
function detectBreaks(candles,rawHighs,rawLows,priorDirection){const d=closed(candles),events=[];for(const h of rawHighs){const after=d.slice(h.index+1);const hit=after.find(c=>Number(c.close)>h.price);if(hit){const pl=rawLows.filter(l=>l.index<h.index).at(-1)||null;events.push({direction:'bullish',kind:priorDirection==='bearish'?'CHoCH':'BOS',level:h.price,index:d.indexOf(hit),time:hit.openTime,protectedLow:pl,protectedHigh:null});}}for(const l of rawLows){const after=d.slice(l.index+1);const hit=after.find(c=>Number(c.close)<l.price);if(hit){const ph=rawHighs.filter(h=>h.index<l.index).at(-1)||null;events.push({direction:'bearish',kind:priorDirection==='bullish'?'CHoCH':'BOS',level:l.price,index:d.indexOf(hit),time:hit.openTime,protectedHigh:ph,protectedLow:null});}}events.sort((a,b)=>a.index-b.index);const latest=events.at(-1)||null;return{bos:latest?.kind==='BOS'?latest:null,choch:latest?.kind==='CHoCH'?latest:null,latest};}
function buildHierarchy(highs,lows,breaks){const all=[...highs,...lows].sort((a,b)=>a.index-b.index);const ext=new Set();const b=breaks?.latest;if(b){if(b.direction==='bullish'){if(b.protectedLow)ext.add(`swing_low:${b.protectedLow.index}`);const h=highs.filter(x=>x.index<=b.index).at(-1);if(h)ext.add(`swing_high:${h.index}`);}else{if(b.protectedHigh)ext.add(`swing_high:${b.protectedHigh.index}`);const l=lows.filter(x=>x.index<=b.index).at(-1);if(l)ext.add(`swing_low:${l.index}`);}}if(!ext.size)all.slice(-2).forEach(x=>ext.add(`${x.type}:${x.index}`));const internal=[],external=[];for(const x of all){const isExternal=ext.has(`${x.type}:${x.index}`);(isExternal?external:internal).push({...x,liquidityClass:isExternal?'external':'internal'});}return{internal,external};}
function analyzeStructure(candles,options={}){const d=closed(candles),strength=Number(options.swingStrength)||DEFAULT_SWING_LENGTH,rawH=findSwingHighs(d,strength),rawL=findSwingLows(d,strength),highs=classifyHighs(rawH),lows=classifyLows(rawL),direction=determineDirection(highs,lows),breaks=detectBreaks(d,rawH,rawL,direction),hierarchy=buildHierarchy(highs,lows,breaks);const protectedLow=breaks.latest?.protectedLow||(direction==='bullish'?lows.filter(x=>x.classification==='HL').at(-1):null);const protectedHigh=breaks.latest?.protectedHigh||(direction==='bearish'?highs.filter(x=>x.classification==='LH').at(-1):null);return{valid:d.length>=30,direction,swings:{highs,lows},hierarchy,latest:{high:highs.at(-1)||null,low:lows.at(-1)||null},breaks,protectedLow:protectedLow||null,protectedHigh:protectedHigh||null,candlesAnalyzed:d.length,generatedAt:new Date().toISOString()};}
function analyzeAllStructures(marketData){if(!marketData?.timeframes)throw new Error('Market data with timeframes is required');const out={};for(const tf of TIMEFRAMES)out[tf]=analyzeStructure(marketData.timeframes[tf]?.candles||[]);return out;}
module.exports={TIMEFRAMES,findSwingHighs,findSwingLows,analyzeStructure,analyzeAllStructures};
